version: '2'
services:
  node:
    container_name: bk-api
    build: 
      context: .
      dockerfile: node.dockerfile
    ports:
     - "3000:3000"
    networks:
      - nodeapp-network
      
  mongodb:
    container_name: nashamongo
    image: mongo
    command: mongod --smallfiles
    networks:
      - nodeapp-network

networks:
  nodeapp-network:
    driver: bridge