---
inventory:  
  build: .
  command: npm start
  ports:
  - "8080:8080"
  links:
  - mongodb
  - mongodb:mongodb.localhost.bookapi
  environment:
    - NODE_ENV=production
    - MONGODB_ADDRESS=mongodb
mongodb:  
  image: mongo
